### ISSUE TITLE
运行./wakeup_trigger_start.sh报错

### ISSUE THREAD

**Issue by Tracy6465** [MyDuerOS/DuerOS-Python-Client#10]
我看代码里面有snowboydetect这个文件，
Traceback (most recent call last):
  File "./app/wakeup_trigger_main.py", line 21, in <module>
    from app.snowboy import snowboydecoder
  File "/home/chris/DuerOS-Python-Client/app/snowboy/snowboydecoder.py", line 5, in <module>
    from . import snowboydetect
snowboydetect
  File "/home/chris/DuerOS-Python-Client/app/snowboy/snowboydetect.py", line 20, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/chris/DuerOS-Python-Client/app/snowboy/snowboydetect.py", line 17, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _snowboydetect

**Comment by pengge** [comment]
需要重新编译snowboy

**Comment by yeyupiaoling** [comment]
我也是这个问题，怎么编译：snowboy

**Comment by yeyupiaoling** [comment]
@pengge 我是用Ubuntu 16.04桌面版，不是树莓派

**Comment by kaaanata** [comment]
https://github.com/kitt-ai/snowboy

**Compile a Python Wrapper**
```
cd swig/Python
make
```
SWIG will generate a `_snowboydetect.so` file and a simple (but hard-to-read) python wrapper `snowboydetect.py`. We have provided a higher level python wrapper `snowboydecoder.py` on top of that.

Feel free to adapt the Makefile in swig/Python to your own system's setting if you cannot make it.

**Comment by happysmile12321** [comment]
> @pengge 我是用Ubuntu 16.04桌面版，不是树莓派

你编译好了吗？我是arch linux。虽然AUR里面有这个包不过下载太慢。我想自己编译发现链接的时候少静态链接库。我想如果你编译成功的话我就从虚拟机的ubuntu里面把那个链接库拿到arch里来。

**Comment by happysmile12321** [comment]
> 我也是这个问题，怎么编译：snowboy

你编译好了吗？我是arch linux。虽然AUR里面有这个包不过下载太慢。我想自己编译发现链接的时候少静态链接库。我想如果你编译成功的话我就从虚拟机的ubuntu里面把那个链接库拿到arch里来。

**Comment by yeyupiaoling** [comment]
@happysmile12321 编译过了，不过很久之前的事情了。不是使用虚拟机的，我是在真机上编译的
