### ISSUE TITLE
gi.require_version('Gst', '1.0') AttributeError: 'module' object has no attribute 'require_version'

### ISSUE THREAD

**Issue by yllyx** [MyDuerOS/DuerOS-Python-Client#14]
Ubuntu16.04 pc机上执行下面的命令报错，错误信息如下：
./wakeup_trigger_start.sh 
Traceback (most recent call last):
  File "./app/wakeup_trigger_main.py", line 19, in <module>
    from app.framework.player import Player
  File "/home/yllyx/Downloads/DuerOS-Python-Client/app/framework/player.py", line 9, in <module>
    gi.require_version('Gst', '1.0')
AttributeError: 'module' object has no attribute 'require_version'

有谁碰到类似的问题的？？？

**Comment by feiyx** [comment]
同遇到

**Comment by feiyx** [comment]
![x m_ mf5hal0iuyrut 6p 8](https://user-images.githubusercontent.com/11736470/34248425-f6f62b24-e670-11e7-8f5a-16259151404f.png)

**Comment by snailbull** [comment]
我也遇到了这个gi的问题，尝试装了pygobject，pycairo等等，依旧不行。
请这个gi.repository要怎么解决。
pip install gi之后，gi下面也是空的，根本没有repository和require_version。

**Comment by HuangDayu** [comment]
https://dueros.baidu.com/forum/topic/show/262219
