### ISSUE TITLE
master分支 运行 wakeup_trigger_start.sh  报错

### ISSUE THREAD

**Issue by githublqs** [MyDuerOS/DuerOS-Python-Client#23]
master分支 运行 wakeup_trigger_start.sh  报错
CLIENT_ID,CLIENT_SECRET已经申请过了，并且 app/auth.py main函数里调用的是auth.auth_request(CLIENT_ID, CLIENT_SECRET)

ERROR:root:
Traceback (most recent call last):
  File "/home/lqs/DuerOS-Python-Client/sdk/dueros_core.py", line 176, in run
    self.__run()
  File "/home/lqs/DuerOS-Python-Client/sdk/dueros_core.py", line 203, in __run
    downchannel_response = conn.get_response(downchannel_id)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 312, in get_response
    return HTTP20Response(stream.getheaders(), stream)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/stream.py", line 230, in getheaders
    self._recv_cb(stream_id=self.stream_id)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 771, in _recv_cb
    self._single_read()
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 665, in _single_read
    self._sock.fill()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/bufsocket.py", line 169, in fill
    raise ConnectionResetError()
ConnectionResetError

**Comment by hetaoxiaoming** [comment]
解决了亲？？
