### ISSUE TITLE
可以在mac上开发么

### ISSUE THREAD

**Issue by Stepin2** [MyDuerOS/DuerOS-Python-Client#5]

**Comment by easying001** [comment]
目前不行，之前有遇到 mac自带python2.7里面的openssl版本过低，估计需要重编mac上的python库

**Comment by SnowyTomorrow** [comment]
@easying001 那是不将Mac上的python卸载重装就可以，还有我pip install python-gi 提示找不到版本，而我又找不到python-gi的官网地址，希望能帮忙指导一下

**Comment by hongyu315** [comment]
有谁在 Mac上尝试成功过吗？

**Comment by hongyu315** [comment]
Mac上Python 从3.6切换回2.7，目前还有一大堆报错，求官方支持

**Comment by witmax** [comment]
Mac上没成功，挂在这步了

uerOS-Python-Client$ ./enter_trigger_start.sh
Traceback (most recent call last):
  File "./app/enter_trigger_main.py", line 9, in <module>
    from app.framework.player import Player
  File "/Users/maplenan/DuerOS-Python-Client/app/framework/player.py", line 9, in <module>
    gi.require_version('Gst', '1.0')
AttributeError: 'module' object has no attribute 'require_version'

**Comment by Nyloner** [comment]
修改了一个Mac版
https://github.com/Nyloner/DuerOS-Python-Client-For-Mac

尝试用gstreamer播放，没有声音，将gstreamer换掉了。
Snowboy需要重新编译。

**Comment by feiyx** [comment]
在window 上遇到一个问题，就是from gi.repository import Gst 找不到，重新编译了gstreamer和GObject，仍然找不到。
_"D:\program files\python27\python.exe" D:/java/workspace/workspace04_open/DuerOS-Python-Client/app/wakeup_trigger_main.py
Traceback (most recent call last):
  File "D:/java/workspace/workspace04_open/DuerOS-Python-Client/app/wakeup_trigger_main.py", line 18, in <module>
    from app.framework.player import Player
  File "D:\java\workspace\workspace04_open\DuerOS-Python-Client\app\framework\player.py", line 9, in <module>
    gi.require_version('Gst', '1.0')
AttributeError: 'module' object has no attribute 'require_version'_
