### ISSUE TITLE
error after cloning new version

### ISSUE THREAD

**Issue by athosism** [MyDuerOS/DuerOS-Python-Client#8]
pi@raspberrypi:~/DuerOS-Python-Client $ ./wakeup_trigger_start.sh
Traceback (most recent call last):
  File "./app/wakeup_trigger_main.py", line 21, in <module>
    from app.snowboy import snowboydecoder
  File "/home/pi/DuerOS-Python-Client/app/snowboy/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/pi/DuerOS-Python-Client/app/snowboy/snowboydetect.py", line 17, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/DuerOS-Python-Client/app/snowboy/snowboydetect.py", line 16, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/local/python2.7.14/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _snowboydetect

**Comment by athosism** [comment]
git checkout raspberry-dev
